import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const utilsPath = path.join(__dirname, '../src/lib/utils.ts');

const servicesCode = `export const SERVICES: ServiceItem[] = [
  // 1. Sexual Health (Men)
  {
    slug: 'erectile-dysfunction',
    name: 'Erectile Dysfunction Treatment',
    category: 'sexual-health-men',
    priority: 1,
    tag: 'ED Treatment',
    meta: 'Performance & Confidence',
    summary: 'Advanced diagnosis and treatment to restore performance and confidence.',
    description: 'Targeted care for difficulty achieving or maintaining an erection. We provide advanced diagnosis and personalized treatments to help restore sexual health and confidence.',
    problem: 'Difficulty achieving or maintaining erection',
    whoItsFor: ['Men experiencing difficulty achieving or maintaining erections', 'Individuals facing performance anxiety or stress', 'Patients with underlying conditions affecting sexual health'],
    benefits: ['Restores sexual performance and confidence', 'Addresses root causes for long-term improvement', 'Improves relationship satisfaction', 'Provides a safe and confidential care environment'],
    concerns: ['Erectile dysfunction', 'Performance anxiety', 'Loss of confidence in sexual situations'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'sage' },
  },
  {
    slug: 'premature-ejaculation',
    name: 'Premature Ejaculation Treatment',
    category: 'sexual-health-men',
    priority: 2,
    tag: 'PE Treatment',
    meta: 'Control & Satisfaction',
    summary: 'Effective solutions to improve control and sexual satisfaction.',
    description: 'Comprehensive approach to managing early ejaculation and lack of control. Our treatments are designed to improve timing, control, and overall sexual satisfaction.',
    problem: 'Early ejaculation and lack of control',
    whoItsFor: ['Men experiencing early ejaculation', 'Individuals seeking better control during intimacy', 'Couples looking to improve their sexual experience'],
    benefits: ['Improves control and timing', 'Enhances sexual satisfaction for both partners', 'Reduces performance anxiety', 'Customized treatment plans based on individual needs'],
    concerns: ['Premature ejaculation', 'Lack of control', 'Anxiety related to performance'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'monitor-smartphone', tone: 'mist' },
  },
  {
    slug: 'male-sexual-wellness',
    name: 'Male Sexual Wellness',
    category: 'sexual-health-men',
    priority: 3,
    tag: 'Wellness',
    meta: 'Evaluation & Balance',
    summary: 'Complete evaluation of sexual health including lifestyle and hormones.',
    description: 'A holistic assessment of male sexual health, addressing issues like low libido, fatigue, and hormonal imbalance to improve overall well-being and vitality.',
    problem: 'Low libido, fatigue, hormonal imbalance',
    whoItsFor: ['Men experiencing low sex drive or fatigue', 'Individuals suspecting hormonal imbalances', 'Those wanting a comprehensive sexual health checkup'],
    benefits: ['Identifies and treats root causes of low libido', 'Restores energy levels and vitality', 'Balances hormones for improved health', 'Integrates lifestyle and nutritional guidance'],
    concerns: ['Low libido', 'Chronic fatigue', 'Hormonal imbalances like low testosterone'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'gold' },
  },
  {
    slug: 'ejaculation-disorders',
    name: 'Ejaculation Disorders Treatment',
    category: 'sexual-health-men',
    priority: 4,
    tag: 'Disorders',
    meta: 'Reproductive Health',
    summary: 'Treatment for ejaculation-related conditions to improve reproductive health.',
    description: 'Specialized care for conditions such as pain during ejaculation, delayed ejaculation, or blood in semen, aimed at improving both comfort and reproductive health.',
    problem: 'Pain, delayed ejaculation, blood in semen',
    whoItsFor: ['Men experiencing pain during ejaculation', 'Individuals with delayed ejaculation', 'Patients noticing blood in their semen'],
    benefits: ['Alleviates pain and discomfort', 'Improves overall reproductive health', 'Addresses potential underlying infections or conditions', 'Provides peace of mind through thorough diagnostics'],
    concerns: ['Painful ejaculation', 'Delayed ejaculation', 'Hematospermia (blood in semen)'],
    careModes: ['clinic', 'lab-coordination'],
    visual: { type: 'icon', icon: 'test-tube-diagonal', tone: 'linen' },
  },

  // 2. Male Fertility
  {
    slug: 'male-infertility',
    name: 'Male Infertility Treatment',
    category: 'male-fertility',
    priority: 5,
    tag: 'Infertility',
    meta: 'Reproductive Outcomes',
    summary: 'Comprehensive fertility care to improve reproductive outcomes.',
    description: 'Advanced diagnostic and treatment protocols for men facing issues like low sperm count or poor sperm quality, focused on improving the chances of conception.',
    problem: 'Low sperm count, poor quality',
    whoItsFor: ['Men diagnosed with infertility', 'Couples struggling to conceive due to male factors', 'Individuals needing advanced reproductive care'],
    benefits: ['Improves sperm count and quality', 'Enhances overall fertility potential', 'Provides clear treatment pathways based on diagnostics', 'Supports couples in their conception journey'],
    concerns: ['Male factor infertility', 'Poor sperm morphology or motility', 'Difficulty conceiving'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'mist' },
  },
  {
    slug: 'low-sperm-count',
    name: 'Low Sperm Count Treatment',
    category: 'male-fertility',
    priority: 6,
    tag: 'Oligospermia',
    meta: 'Targeted Solutions',
    summary: 'Targeted solutions to increase sperm count and quality.',
    description: 'Personalized treatment plans addressing oligospermia (low sperm count) caused by lifestyle factors, hormonal issues, or other underlying conditions.',
    problem: 'Oligospermia due to lifestyle or hormonal issues',
    whoItsFor: ['Men diagnosed with low sperm count', 'Individuals with hormonal imbalances affecting fertility', 'Patients looking to optimize their fertility through lifestyle changes'],
    benefits: ['Specifically targets causes of low sperm count', 'Balances hormones to support sperm production', 'Provides actionable lifestyle and nutritional advice', 'Monitors progress through regular testing'],
    concerns: ['Oligospermia', 'Hormonal imbalance affecting fertility', 'Lifestyle factors impacting sperm health'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'test-tube-diagonal', tone: 'sage' },
  },
  {
    slug: 'fertility-diagnostic-testing',
    name: 'Fertility Diagnostic Testing',
    category: 'male-fertility',
    priority: 7,
    tag: 'Diagnostics',
    meta: 'Analysis & Testing',
    summary: 'Includes semen analysis, hormone testing, ultrasound, and genetic tests.',
    description: 'Comprehensive diagnostic services to identify the root causes of unknown fertility issues. Our advanced testing provides a clear picture of your reproductive health.',
    problem: 'Unknown fertility issues',
    whoItsFor: ['Couples beginning their fertility evaluation', 'Men needing semen analysis or hormone testing', 'Individuals requiring advanced genetic or ultrasound evaluations'],
    benefits: ['Provides accurate and comprehensive diagnosis', 'Guides personalized treatment planning', 'Identifies hidden or underlying fertility issues', 'Uses state-of-the-art diagnostic tools'],
    concerns: ['Unknown causes of infertility', 'Need for detailed reproductive health analysis', 'Requirement for specific fertility tests'],
    careModes: ['clinic', 'lab-coordination'],
    visual: { type: 'icon', icon: 'test-tube-diagonal', tone: 'gold' },
  },
  {
    slug: 'early-infertility-screening',
    name: 'Early Infertility Screening',
    category: 'male-fertility',
    priority: 8,
    tag: 'Screening',
    meta: 'Early Detection',
    summary: 'Early detection and prevention-focused fertility care.',
    description: 'Proactive screening for individuals experiencing early symptoms like erectile dysfunction or fatigue, aimed at early detection and preserving future fertility.',
    problem: 'Early symptoms like ED, fatigue',
    whoItsFor: ['Men wanting to proactively check their fertility', 'Individuals with symptoms like ED or fatigue wanting to rule out fertility impacts', 'Those planning for future parenthood'],
    benefits: ['Identifies potential issues before they become severe', 'Allows for early intervention and prevention', 'Provides peace of mind', 'Integrates with overall sexual wellness checks'],
    concerns: ['Proactive fertility health', 'Impact of early symptoms on future fertility', 'Preventive care'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'monitor-smartphone', tone: 'linen' },
  },

  // 3. Female Fertility & Gynecology
  {
    slug: 'pcos-pcod-treatment',
    name: 'PCOS / PCOD Treatment',
    category: 'female-fertility',
    priority: 9,
    tag: 'PCOS/PCOD',
    meta: 'Hormonal Balance',
    summary: 'Personalized care to restore hormonal balance and fertility.',
    description: 'Specialized treatment for Polycystic Ovary Syndrome (PCOS) and PCOD, addressing hormonal imbalances, irregular periods, and their impact on fertility.',
    problem: 'Hormonal imbalance, irregular periods',
    whoItsFor: ['Women diagnosed with PCOS or PCOD', 'Individuals experiencing irregular menstrual cycles', 'Patients struggling with PCOS-related infertility'],
    benefits: ['Restores hormonal balance and cycle regularity', 'Improves chances of natural conception', 'Manages symptoms like weight gain or acne', 'Provides comprehensive lifestyle and medical management'],
    concerns: ['PCOS / PCOD', 'Irregular menstrual cycles', 'Hormonal imbalances'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'sage' },
  },
  {
    slug: 'female-infertility',
    name: 'Female Infertility Treatment',
    category: 'female-fertility',
    priority: 10,
    tag: 'Infertility',
    meta: 'Advanced Care',
    summary: 'Advanced treatments addressing root causes of infertility.',
    description: 'Comprehensive evaluation and treatment for women having difficulty conceiving. We focus on identifying and treating the root causes to improve reproductive success.',
    problem: 'Difficulty conceiving',
    whoItsFor: ['Women struggling to conceive naturally', 'Patients needing advanced fertility diagnostics', 'Individuals requiring personalized fertility treatment plans'],
    benefits: ['Identifies specific causes of female infertility', 'Offers advanced, evidence-based treatments', 'Supports overall reproductive health', 'Provides emotional and medical support throughout the process'],
    concerns: ['Female factor infertility', 'Unexplained infertility', 'Difficulty getting pregnant'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'mist' },
  },
  {
    slug: 'fibroid-treatment',
    name: 'Fibroid Treatment',
    category: 'female-fertility',
    priority: 11,
    tag: 'Fibroids',
    meta: 'Uterine Health',
    summary: 'Diagnosis and treatment to improve uterine health.',
    description: 'Expert care for uterine fibroids that may be causing pain, heavy bleeding, or affecting fertility. Our treatments are designed to improve uterine health and overall well-being.',
    problem: 'Uterine fibroids affecting fertility',
    whoItsFor: ['Women diagnosed with uterine fibroids', 'Patients experiencing symptoms like heavy bleeding or pelvic pain', 'Individuals whose fertility is impacted by fibroids'],
    benefits: ['Manages and treats fibroid symptoms', 'Improves uterine health for better fertility outcomes', 'Offers both medical and minimally invasive options', 'Reduces pain and discomfort'],
    concerns: ['Uterine fibroids', 'Heavy menstrual bleeding', 'Pelvic pain related to fibroids'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'house', tone: 'gold' },
  },
  {
    slug: 'endometriosis-treatment',
    name: 'Endometriosis Treatment',
    category: 'female-fertility',
    priority: 12,
    tag: 'Endometriosis',
    meta: 'Symptom Management',
    summary: 'Specialized care to manage symptoms and improve fertility.',
    description: 'Comprehensive management of endometriosis, focusing on alleviating painful periods, managing symptoms, and improving fertility outcomes for affected women.',
    problem: 'Painful periods and infertility',
    whoItsFor: ['Women suffering from painful periods or pelvic pain', 'Patients diagnosed with endometriosis', 'Individuals struggling with fertility due to endometriosis'],
    benefits: ['Reduces pain and improves quality of life', 'Manages disease progression', 'Optimizes fertility for those trying to conceive', 'Provides specialized, compassionate care'],
    concerns: ['Endometriosis', 'Severe menstrual pain', 'Infertility linked to endometriosis'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'linen' },
  },
  {
    slug: 'gynecological-care',
    name: 'Gynecological Care',
    category: 'female-fertility',
    priority: 13,
    tag: 'Gynecology',
    meta: 'Women’s Health',
    summary: 'Complete women’s health services including routine checkups and disorder management.',
    description: 'Comprehensive gynecological services addressing menstrual disorders, infections, ovarian cysts, and providing overall health care for women at all stages of life.',
    problem: 'Menstrual disorders, infections, cysts',
    whoItsFor: ['Women needing routine gynecological exams', 'Patients with menstrual irregularities or infections', 'Individuals managing conditions like ovarian cysts'],
    benefits: ['Provides comprehensive preventive care', 'Effectively treats infections and menstrual disorders', 'Monitors and manages cysts and other common issues', 'Promotes overall women’s health and wellness'],
    concerns: ['Menstrual irregularities', 'Vaginal infections', 'Ovarian cysts', 'Routine women’s health checks'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'mist' },
  },

  // 4. Couple Care
  {
    slug: 'couple-fertility-consultation',
    name: 'Couple Fertility Consultation',
    category: 'couple-care',
    priority: 14,
    tag: 'Consultation',
    meta: 'Joint Evaluation',
    summary: 'Joint evaluation and treatment planning for couples.',
    description: 'A collaborative approach to fertility care, offering joint evaluation and coordinated treatment planning for couples experiencing difficulty conceiving.',
    problem: 'Difficulty conceiving together',
    whoItsFor: ['Couples beginning their fertility journey', 'Partners who both need fertility evaluation', 'Those seeking a coordinated, joint treatment plan'],
    benefits: ['Evaluates both partners simultaneously for faster answers', 'Creates a unified, coordinated treatment plan', 'Reduces stress by addressing fertility as a team', 'Provides comprehensive support for the couple'],
    concerns: ['Couple infertility', 'Need for joint reproductive evaluation', 'Coordinated treatment planning'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'house', tone: 'sage' },
  },
  {
    slug: 'parenthood-planning',
    name: 'Parenthood Planning',
    category: 'couple-care',
    priority: 15,
    tag: 'Planning',
    meta: 'Step-by-Step Guidance',
    summary: 'Step-by-step guidance toward successful pregnancy.',
    description: 'Expert guidance and structured planning for couples facing confusion or delays in conception, helping them navigate their path to successful parenthood.',
    problem: 'Confusion or delays in conception',
    whoItsFor: ['Couples planning to start a family', 'Individuals confused about the conception process', 'Partners experiencing delays but not yet diagnosed with infertility'],
    benefits: ['Provides a clear, step-by-step roadmap to conception', 'Educates couples on optimal timing and practices', 'Reduces anxiety related to conception delays', 'Offers professional support and monitoring'],
    concerns: ['Pre-conception planning', 'Delays in getting pregnant', 'Understanding the conception window'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'monitor-smartphone', tone: 'gold' },
  },

  // 5. Lifestyle & Wellness
  {
    slug: 'stress-fertility-management',
    name: 'Stress & Fertility Management',
    category: 'lifestyle-wellness',
    priority: 16,
    tag: 'Stress Management',
    meta: 'Reproductive Health',
    summary: 'Programs to reduce stress and improve fertility.',
    description: 'Holistic programs designed to manage and reduce stress levels, recognizing the significant impact stress can have on reproductive health and fertility outcomes.',
    problem: 'Stress affecting reproductive health',
    whoItsFor: ['Individuals experiencing high stress levels', 'Couples whose fertility may be impacted by lifestyle stress', 'Patients looking for holistic support during fertility treatments'],
    benefits: ['Lowers stress levels to improve overall health', 'Positively impacts hormonal balance and fertility', 'Teaches effective coping and relaxation techniques', 'Enhances the success rates of other fertility treatments'],
    concerns: ['Stress-induced fertility issues', 'Anxiety related to trying to conceive', 'Need for holistic support'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'house', tone: 'linen' },
  },
  {
    slug: 'hormonal-lifestyle-management',
    name: 'Hormonal & Lifestyle Management',
    category: 'lifestyle-wellness',
    priority: 17,
    tag: 'Lifestyle',
    meta: 'Long-term Health',
    summary: 'Lifestyle-based treatment for long-term health and hormonal balance.',
    description: 'Comprehensive management of lifestyle factors such as obesity, alcohol consumption, smoking, and overall hormonal imbalance to improve long-term health and fertility.',
    problem: 'Obesity, alcohol, smoking, imbalance',
    whoItsFor: ['Individuals needing to optimize their lifestyle for fertility', 'Patients struggling with obesity or metabolic issues', 'Those looking to quit smoking or reduce alcohol for reproductive health'],
    benefits: ['Improves overall physical health and hormonal balance', 'Increases chances of conception naturally', 'Provides structured guidance for healthy habit formation', 'Supports long-term reproductive and general wellness'],
    concerns: ['Lifestyle impacts on fertility', 'Obesity and hormonal imbalance', 'Need for structured lifestyle changes'],
    careModes: ['clinic', 'online', 'lab-coordination'],
    visual: { type: 'icon', icon: 'stethoscope', tone: 'mist' },
  },
  {
    slug: 'nutrition-sexual-health',
    name: 'Nutrition & Sexual Health',
    category: 'lifestyle-wellness',
    priority: 18,
    tag: 'Nutrition',
    meta: 'Diet & Supplements',
    summary: 'Diet and supplement guidance for better performance and health.',
    description: 'Targeted nutritional counseling and supplement guidance tailored to improve sexual health, performance, and overall vitality, addressing poor diet impacts.',
    problem: 'Poor diet affecting performance',
    whoItsFor: ['Individuals looking to improve sexual health through diet', 'Patients needing guidance on supplements for fertility', 'Those experiencing performance issues related to poor nutrition'],
    benefits: ['Optimizes nutritional intake for sexual health', 'Provides evidence-based supplement recommendations', 'Boosts energy and performance naturally', 'Complements other medical treatments effectively'],
    concerns: ['Nutritional deficiencies affecting sexual health', 'Need for specific diet plans for fertility', 'Understanding the right supplements to take'],
    careModes: ['clinic', 'online'],
    visual: { type: 'icon', icon: 'test-tube-diagonal', tone: 'sage' },
  }
];`;

let content = fs.readFileSync(utilsPath, 'utf8');

// replace the SERVICES array
const startIdx = content.indexOf('export const SERVICES: ServiceItem[] = [');
const endIdx = content.indexOf('export const ORDERED_SERVICES =');

if (startIdx !== -1 && endIdx !== -1) {
    content = content.substring(0, startIdx) + servicesCode + '\n\n' + content.substring(endIdx);
    fs.writeFileSync(utilsPath, content);
    console.log('Successfully updated SERVICES in utils.ts');
} else {
    console.error('Could not find SERVICES array boundaries');
}
